### ISSUE TITLE
Vue3 Options API Support

### ISSUE THREAD

**Issue by haritha2112** [alexander-heimbuch/redux-vuex#24]
We are upgrading our Project to Vue3, but we are continuing to use Options API. When trying to upgrade this library, we couldn't get it working as this seems to be have re-written exclusively for Composition API. Was this intentional? If so, are there any plans to provide support for Options API as well?

**Comment by alexander-heimbuch** [comment]
Hey,

since the Vue3 API hasn't changed this should be possible. I could provide a legacy connector if that helps.

**Comment by haritha2112** [comment]
Could you provide some insight on how the legacy connector would work?

**Comment by alexander-heimbuch** [comment]
It would/could like this:

```
import { createApp } from "vue";
import { connect } from 'redux-vuex/legacy';

import App from "./App.vue";
import { store, actions } from "./store";


const app = createApp(App);

connect({ app, store, actions });

app.mount("#app");
```


I also have a  first implementation available in case you want to try out the legacy connector.

**Comment by DV8FromTheWorld** [comment]
Would the legacy connector and the new `mapState` composition function be interop with eachother (either could be used)?

**Comment by alexander-heimbuch** [comment]
Unfortunately not, the new `mapState` uses reactive properties, the legacy one adds it to directly to the `data` property and mutates it to trigger Vue's change detection. That is btw. also the reason why I recommend using the hooks since they will be much more performant. So you would have to adjust the imports for `mapState` as well to `import { mapState } from "redux-vuex/legacy";`

**Comment by DV8FromTheWorld** [comment]
Alrighty. 

We are eagerly awaiting this support to continue our Vue3 migration process.

**Comment by alexander-heimbuch** [comment]
I've just published `v3.0.0-beta.4` including the legacy connectors. Feel free to ping me if something doesn't work.

**Comment by haritha2112** [comment]
Hi! Thank you so much for providing the legacy connectors.

While trying out the legacy connecter as mentioned [here](https://github.com/alexander-heimbuch/redux-vuex/issues/24#issuecomment-902783882) in our code, we encountered an issue. A type error was thrown in the console which said `r.default` is not a function in `legacy.js` file. Upon digging a little more, we realized this has to do with the way `set` was imported in `legacy/mixin.ts` file: 

`import set from 'set-value'`

If we change the above line to: `import * as set from 'set-value'`, we **will not** see this issue. Confirmed this by updating the minified legacy.js file we had in our node-modules to be `r(t._data, e, i(o))` instead of `r.default(t._data, e, i(o))`. Things were working perfectly well after that.

**Comment by alexander-heimbuch** [comment]
Good to know. As soon as I’m getting hands on my working machine I will update the library. Thanks for the feedback 👍

**Comment by alexander-heimbuch** [comment]
I've just released the fix in `beta.5` :)

**Comment by DV8FromTheWorld** [comment]
> Would the legacy connector and the new mapState composition function be interop with eachother (either could be used)?


As a note, we accomplished this by using `provideStore` and `connect` at the same time:
```js
import { provideStore from 'redux-vuex'
import { connect } from 'redux-vuex/legacy'

provideStore({ app, store })
connect({ app, store })
```

However, one problem we encountered when doing this is that the Vue Composition side of this library relies [directly on `@vue/runtime-core`](https://github.com/alexander-heimbuch/redux-vuex/blob/master/src/map-state.ts#L2) instead of using `import { ... } from 'vue'`.

This means that it will break your application if you do the above usage of both connectors while relying on the `@vue/compat` package because the recommended way to use `@vue/compat` is to setup a webpack alias to replace `from 'vue'` with `from '@vue/compat'` and the direct reliance on `'@vue/runtime-core'` sidesteps this alias.

We used https://www.npmjs.com/package/patch-package to update the `/node_modules/redux-vuex/index.js` file to rely on `@vue/compat` instead until we're done moving to Vue3.
