### ISSUE TITLE
Binding Store to the Vue Instance

### ISSUE THREAD

**Issue by arunrreddy** [alexander-heimbuch/redux-vuex#9]
With vuex, we create a store and export it. In the main.js file where we are mounting the application, we bind the store the main element like so.

```
new Vue({
    router,
    store,
    el: '#app',
    render: createElement => createElement(Main)
});
```

What is the equivalent of this in redux-vuex? How does the store bind to the main Vue instance?

I can see the use of the connect function.
```
connect({
  Vue,
  store,
  actions, // optional
  binding // optional: public store binding on vue instance (by default 'store')
});
```
I want to know how it maps this store to the main Vue instance. Does it require any extra configuration to be written or is the store variables available using import { mapState } from 'redux-vuex' in any component?

**Comment by alexander-heimbuch** [comment]
Hey,
`redux-vuex` uses behind the scenes a Vue mixin which is configured by calling `connect`. Every component has access to the store, you can access it by default via `this.store`(or by the binding you defined): https://github.com/alexander-heimbuch/redux-vuex/blob/master/src/mixin.js#L28
That is btw. also the reason why I simply can't use the store property in the Vue instance because I need to have access to the created hook to prepare the store bindings.

The `mapState` helper is simply a helper to create bindings between the immutable store and the reactive data of the Vue instance. It is also available via `this.mapState`: https://github.com/alexander-heimbuch/redux-vuex/blob/master/src/mixin.js#L36

Hope that helps :)
